FROM ubuntu:latest

MAINTAINER Karan Kapoor <karan.kapoor@softuvo.com>

RUN apt-get update
#RUN apt-get install -y autoconf pkg-config libssl-dev
#RUN pecl install mongodb-1.2.2
#RUN docker-php-ext-install bcmath
#RUN echo "extension=mongodb.so" >> /usr/local/etc/php/conf.d/mongodb.ini
ARG DEBIAN_FRONTEND=noninteractive
###########Install Laravel dependencies###########
RUN apt-get update \
    && apt install -y gcc \
                git \
  && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
        software-properties-common \
#    add-apt-repository ppa:ondrej/php && \
#        php7.2 \
#        php7.2-fpm \
#        php7.2-common \
        git  \
        wget \
        curl 
##########################################################
#RUN apt-get update && apt-get install -y software-properties-common  \
   # && LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php \
#    && apt-get update \
# add php repo
RUN LC_ALL=C.UTF-8 apt-add-repository -y ppa:ondrej/php && apt-get update -y
# add php
#See makefile
#ARG PHP_VERSION
#ARG WEB_SERVER
#ENV PHP_VERSION=${7.2} \
   # WEB_SERVER=${WEB_SERVER} \
   # DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    php \
    php7.2-cli \
    #php7.2-fpm \
    mcrypt \
        curl \
       php7.2-curl \
      php7.2-mbstring  \
    && mkdir /run/php 
#    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
#####################
#RUN docker-php-ext-install iconv mcrypt mbstring \
#    && docker-php-ext-install zip \
#    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
#    && docker-php-ext-install gd
########## Install Composer
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
############ Install dependencies
#RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
####### install node & dependencies#############
RUN apt-get update && apt-get install -y \
      curl \
      nodejs \
      git



########## invoke nvm to install node
#RUN cp -f ~/.nvm/nvm.sh ~/.nvm/nvm-tmp.sh; \
#    echo "nvm install 10.20.1; nvm alias default 10.20.1" >> ~/.nvm/nvm-tmp.sh; \
#    sh ~/.nvm/nvm-tmp.sh; \
#    rm ~/.nvm/nvm-tmp.sh;

ARG DEBIAN_FRONTEND=noninteractive

############ Install Nginx##################
RUN \
  apt-add-repository -r ppa:nginx/stable && \
  apt-get update && \
  apt-get install -y  nginx && \
                #     php-fpm \ 
  rm -rf /var/lib/apt/lists/*
###########Certbot########

RUN apt-add-repository -r ppa:certbot/certbot
RUN apt update
RUN apt install -y python3-certbot-nginx

########################
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]

WORKDIR /var/www/html/jamon
#RUN chown -R www-data:www:data /var/www/html/
#RUN cd .. /
COPY ./jamon /var/www/html/jamon;
