version: '3'
services:
    fphp5:
        build:
         context: ./docode
        container_name: FSW_5
        volumes:
             - ./code:/var/www/html/
             - apacheconf:/etc/apache2/
               # - ./letsencrypt:/etc/letsencrypt
             - apachelogs:/var/logs/apache2/
        ports:
             - 9003:80
             - 9004:443
        networks:
            firstsv_nw:
                ipv4_address: 172.29.1.4
        restart: always
        #        labels:
                #  - "traefik.enable=true"
                #      - "traefik.basic.port=9003"
                #    - "traefik.basic.protocol=http"
                # - "traefik.http.routers.fphp5.rule=Host(`solutions.softuvo.xyz`)"  
      # Tell Traefik to use the port 12345 to connect to `my-container`
      #- traefik.http.services.fphp5.loadbalancer.server.port=9003
                #     - traefik.http.services.fphp5.loadbalancer.server.port=9004
                # - "traefik.admin.frontend.rule=Host:solutions.softuvo.xyz && Path(`/360-solution`)"
                #       - "traefik.frontend.rule=Host:solutions.softuvo.xyz"
                #        - "traefik.http.routers.fphp5.entrypoints=websecure" 
                #              - "traefik.http.routers.api.service=api@internal"
                #              - "traefik.http.routers.fphp5.tls.certresolver=myresolver"
        depends_on:
             - pmysql
               #    php7.2:         
               #   build:
               #   context: ./docode/7.4
               #        container_name: FSW_7.4
               #        volumes:
               #             - ./code:/var/www/html/
               #             - apache7_4:/etc/apache2/
               # - ./letsencrypt:/etc/letsencrypt
               #             - apachelogs:/var/logs/apache2/
               #        ports:
               #             - 9007:80
               #             - 9008:443
               #        networks:
               #            firstsv_nw:
               #                ipv4_address: 172.29.1.6
               #        restart: always
    php7.2:
        build:
         context: ./docode/7.2
        container_name: FSW_7.2
        volumes:
             - ./code:/var/www/html/
             - apache7_2:/etc/apache2/
             -  /etc/letsencrypt:/etc/letsencrypt
             - apachelogs:/var/logs/apache2/
        ports:
             - 9005:80
             - 9006:443
        networks:
            firstsv_nw:
                ipv4_address: 172.29.1.5
        restart: always
        depends_on:
             - pmysql
    pmysql:
        image: mysql:latest
        container_name: pmysql
        command: --default-authentication-plugin=mysql_native_password
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        networks:
            firstsv_nw:
                ipv4_address: 172.29.1.2
        restart: always
        volumes:
            - ./db_data:/var/lib/mysql/
        ports:
             - 3308:3306
        environment:
              Mysql_ROOT_USER: root
              MYSQL_ROOT_PASSWORD: HelmPLesk@90#
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            firstsv_nw:
                ipv4_address: 172.29.1.6
        ports:
            - 8009:80
        restart: always
        environment:
            PMA_HOST: pmysql
            PMA_PORT: 3306
        depends_on:
             - pmysql
    redmine:
        build:
         context: ./redmine
        container_name: redmine
        volumes:
             - ./redmine/code:/var/www/html/
             - redconf:/etc/apache2/
             - ./redmine/default:/etc/redmine/default   
               # - ./letsencrypt:/etc/letsencrypt
             - redlogs:/var/logs/apache2/
        ports:
             - 9010:80
             - 9011:443
        networks:
            firstsv_nw:
                ipv4_address: 172.29.1.14
        restart: always
        depends_on:
             - pmysql
networks:
    firstsv_nw:
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/16
volumes:
    apacheconf:    
    apache7_2:
            #    apache7_4:            
    apachelogs:        
    fp72logs:
    redconf:
    redlogs:
