# pull official base image
FROM ubuntu:latest 

# set and create the appropriate directories
WORKDIR /var/www/html/
ENV APP_HOME=/var/www/html/projectname
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
]

# set environment variables
#ENV PYTHONDONTWRITEBYTECODE 1
#ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apt update \
    && apt install -y gcc \ 
		git \
  && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
		python3-pip \
		python3-dev \
	        wget \	
                software-properties-common \
      		libmysqlclient-dev \
                libpq-dev \
                python-dev \
                vim \
                curl \
                postgresql-client \
                postgresql-contrib \
		unattended-upgrades && \
	rm -r /var/lib/apt/lists/*

#RUN apt-get install libapache2-mod-wsgi -y
RUN pip3 install --upgrade pip 

# install dependencies
RUN apt-get update && apt-get install -y \
      curl \
      npm \
      nodejs \
      git


ARG DEBIAN_FRONTEND=noninteractive
# Install Nginx.
RUN \
  apt-add-repository -r ppa:nginx/stable && \
  apt-get update && \
  apt-get install -y  nginx && \
  rm -rf /var/lib/apt/lists/* 
#  chown -R www-data:www-data /var/lib/nginx

# Define mountable directories.
#VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/etc/nginx/conf.d", "/var/log/nginx", "/var/www/html"]

# Define working directory.

# Define default command.CMD ["nginx"]


#######Certbot####
RUN apt-add-repository -r ppa:certbot/certbot
RUN apt update 
RUN apt install -y python3-certbot-nginx \
         virtualenv


# install nvm
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.24.1/install.sh | sh;

# invoke nvm to install node
RUN cp -f ~/.nvm/nvm.sh ~/.nvm/nvm-tmp.sh; \
    echo "nvm install 10.20.1; nvm alias default 10.20.1" >> ~/.nvm/nvm-tmp.sh; \
    sh ~/.nvm/nvm-tmp.sh; \
    rm ~/.nvm/nvm-tmp.sh;

RUN cd /var/www/html/projectname
#COPY package.json .
RUN npm install -y
RUN npm link @angular/cli@9.0.6 -y
RUN apt install -y certbot
COPY requirements.txt .
RUN pip install -r requirements.txt
# Installing supervisor service and creating directories for copy supervisor configurations
RUN apt-get -y install supervisor && mkdir -p /var/log/supervisor && mkdir -p /etc/supervisor/conf.d
ADD supervisor.conf /etc/supervisor.conf 
#CMD ["nginx", "-g", "daemon off;"]
CMD ["supervisord", "-c", "/etc/supervisor.conf"]   # starting supervisord service
